"""
Sigma, YARA & NIDS Security Rule Generator for SOC Toolkit
Converts detected threat findings into actionable detection rules for SIEM and Endpoint Security.
"""

from datetime import datetime
from typing import Dict, Any, List
from .enums import IOCType, ThreatLevel


class DetectionRuleGenerator:
    """Generate YARA, Sigma, and Snort/Suricata rules from IOC reports"""

    @classmethod
    def generate_sigma(cls, ioc: str, ioc_type: IOCType, title: str = "SOC Threat Alert") -> str:
        """Generate a valid Sigma SIEM detection rule"""
        type_str = ioc_type.value if hasattr(ioc_type, 'value') else str(ioc_type)
        rule_id = f"soc-{hash(ioc) & 0xffffffff:08x}"
        date_str = datetime.now().strftime("%Y/%m/%d")

        if type_str in ("ip", "ipv4", "ipv6"):
            category = "network_connection"
            field_name = "DestinationIp"
        elif type_str in ("domain", "url"):
            category = "dns_query"
            field_name = "QueryName"
            ioc = ioc.replace("https://", "").replace("http://", "").split("/")[0]
        else:
            category = "file_event"
            field_name = "Hashes|contains"

        sigma_rule = f"""title: {title} - {ioc}
id: {rule_id}
status: experimental
description: Automated detection rule generated by SOC Toolkit for indicator {ioc}
author: SOC Toolkit
date: {date_str}
tags:
    - attack.command_and_control
    - attack.t1071
logsource:
    category: {category}
detection:
    selection:
        {field_name}: '{ioc}'
    condition: selection
falsepositives:
    - Known authorized internal infrastructure
level: high
"""
        return sigma_rule

    @classmethod
    def generate_yara(cls, ioc: str, ioc_type: IOCType, rule_name: str = "SOC_Detected_IOC") -> str:
        """Generate a valid YARA rule for hashes or URLs"""
        safe_name = rule_name.replace("-", "_").replace(".", "_")
        date_str = datetime.now().strftime("%Y-%m-%d")

        yara_rule = f"""rule {safe_name} {{
    meta:
        description = "Automated YARA rule generated by SOC Toolkit for {ioc}"
        author = "SOC Toolkit"
        date = "{date_str}"
        reference = "https://github.com/frkndncr/soc-toolkit"

    strings:
        $ioc_string = "{ioc}" ascii wide nocase

    condition:
        $ioc_string
}}
"""
        return yara_rule

    @classmethod
    def generate_nids(cls, ioc: str, ioc_type: IOCType) -> Dict[str, str]:
        """Generate Snort / Suricata and iptables rules"""
        type_str = ioc_type.value if hasattr(ioc_type, 'value') else str(ioc_type)
        rules = {}

        if type_str in ("ip", "ipv4", "ipv6"):
            rules["snort"] = f'alert ip $HOME_NET any -> {ioc} any (msg:"SOC TOOLKIT - Malicious IP Connection to {ioc}"; sid:1000001; rev:1;)'
            rules["suricata"] = f'drop ip $HOME_NET any -> {ioc} any (msg:"SOC TOOLKIT - Dropping Malicious Traffic to {ioc}"; sid:1000002; rev:1;)'
            rules["iptables"] = f'iptables -A INPUT -s {ioc} -j DROP && iptables -A OUTPUT -d {ioc} -j DROP'
            rules["ufw"] = f'ufw deny from {ioc} to any'
        elif type_str in ("domain", "url"):
            domain = ioc.replace("https://", "").replace("http://", "").split("/")[0]
            rules["snort"] = f'alert dns $HOME_NET any -> any 53 (msg:"SOC TOOLKIT - Malicious DNS Query {domain}"; dns.query; content:"{domain}"; sid:1000003; rev:1;)'
            rules["hosts"] = f'0.0.0.0 {domain}'

        return rules
